---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msql-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      restartPolicy: Always
      containers:
        - name: db
          image: db
          imagePullPolicy: Never
          ports:
            - name: db
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: msql-secret
                  key: username
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msql-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: msql-service
spec:
  selector:
    app: db
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
